language: php
branches:
  only:
    - drush
# list any PHP version you want to test against
php:
  # using major version aliases
  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4
install:
  - cd ..
  - git clone --branch=5.x git://github.com/drush-ops/drush.git
  - export UNISH_DRUSH="${PWD}/drush/drush"
  - export PHPUNIT_ARGS=--bootstrap="${PWD}/drush/tests/drush_testcase.inc"
before_script:
  - cd yadd/tests
script: phpunit $PHPUNIT_ARGS --debug --verbose yaddDrushTest.php
