language: php
branches:
  only:
    - drush
# list any PHP version you want to test against
php:
  # using major version aliases
  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4
before_script:
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - pear upgrade-all